
export const translations = {
    ru: {
        main_title: "📊 Merinfo Data Viewer",
        label_select_dataset: "1. Выберите набор данных",
        label_search: "2. Поиск",
        label_sort: "3. Сортировка",
        placeholder_search: "Название, номер, город...",
        sort_name_asc: "Название (А-Я)",
        sort_name_desc: "Название (Я-А)",
        sort_revenue_desc: "Выручка (убыв.)",
        sort_revenue_asc: "Выручка (возр.)",
        sort_profit_before_tax_desc: "Прибыль до налогов (убыв.)",
        sort_profit_before_tax_asc: "Прибыль до налогов (возр.)",
        sort_net_profit_desc: "Чистая прибыль (убыв.)",
        sort_net_profit_asc: "Чистая прибыль (возр.)",
        sort_assets_desc: "Активы (убыв.)",
        sort_assets_asc: "Активы (возр.)",
        sort_date_desc: "Дата регистрации (новые)",
        sort_date_asc: "Дата регистрации (старые)",
        status_waiting: "Ожидание файла...",
        records: "Записей",
        status_analyzing: "Анализ данных...",
        status_reading: "Чтение файла...",
        status_loaded: "Данные успешно загружены",
        status_error_format: "Ошибка: Не удалось распознать формат файла.",
        status_error_read: "Ошибка чтения файла",
        status_error_fetch_list: "Ошибка: Не удалось загрузить список наборов данных.",
        no_data: "Нет данных для отображения",
        showing_first_500: "Показаны первые 500 записей. Используйте поиск или сортировку.",
        active: "Активна",
        unknown: "Неизвестно",
        yes: "Да",
        no: "Нет",
        no_board_data: "Нет данных о совете директоров.",
        company_and_contacts: "🏢 Компания и контакты",
        form: "Форма:",
        registration: "Регистрация:",
        phone: "Телефон:",
        address: "Адрес:",
        city_county: "Город/Округ:",
        taxes: "🧾 Налоги",
        employer: "Работодатель:",
        financials: "💰 Финансы",
        revenue: "Выручка",
        profit_before_tax: "Прибыль до налогов",
        net_profit: "Чистая прибыль",
        total_assets: "Всего активов",
        categories: "🏷️ Категории",
        industry_and_board: "🏭 Деятельность и руководство",
        sni_code: "SNI (Код: {code})",
        board: "👥 Руководство",
        years: "лет",
        advanced_filters: "Расширенные фильтры",
        min: "Мин",
        max: "Макс",
        company_phone: "Телефон компании",
        board_phone: "Телефон руководства",
        any: "Любой",
        has_phone: "Есть",
        no_phone: "Нет",
        sni_description: "SNI Описание",
        categories_filter: "Категории",
        select_placeholder: "Выберите...",
        no_results_found: "Ничего не найдено",
        clear_filters: "Очистить",
        f_skatt_filter: "F-skatt",
        vat_filter: "VAT",
        employer_filter: "Работодатель",
        activity_description_label: "Описание деятельности",
        interaction: "📌 Взаимодействие",
        status: "Статус",
        status_none: "Не выбрано",
        status_interested: "Заинтересован",
        status_not_interested: "Не заинтересован",
        status_callback: "Перезвонить",
        comment: "Комментарий",
        add_comment_placeholder: "Добавьте комментарий...",
        show_favorites_only: "Только избранные",
        filter_by_status: "Фильтр по статусу"
    },
    sv: {
        main_title: "📊 Merinfo Data Viewer",
        label_select_dataset: "1. Välj dataset",
        label_search: "2. Sök",
        label_sort: "3. Sortering",
        placeholder_search: "Namn, organisationsnummer, stad...",
        sort_name_asc: "Namn (A-Ö)",
        sort_name_desc: "Namn (Ö-A)",
        sort_revenue_desc: "Omsättning (fallande)",
        sort_revenue_asc: "Omsättning (stigande)",
        sort_profit_before_tax_desc: "Resultat e. fin. (fallande)",
        sort_profit_before_tax_asc: "Resultat e. fin. (stigande)",
        sort_net_profit_desc: "Årets resultat (fallande)",
        sort_net_profit_asc: "Årets resultat (stigande)",
        sort_assets_desc: "Tillgångar (fallande)",
        sort_assets_asc: "Tillgångar (stigande)",
        sort_date_desc: "Registreringsdatum (nya)",
        sort_date_asc: "Registreringsdatum (gamla)",
        status_waiting: "Väntar på val av dataset...",
        records: "Poster",
        status_analyzing: "Analyserar data...",
        status_reading: "Läser data från GitHub...",
        status_loaded: "Data har laddats framgångsrikt",
        status_error_format: "Fel: Kunde inte tolka filformatet.",
        status_error_read: "Fel vid läsning av data.",
        status_error_fetch_list: "Fel: Kunde inte ladda listan med dataset.",
        no_data: "Ingen data att visa",
        showing_first_500: "Visar de första 500 posterna. Använd sök eller sortering.",
        active: "Aktivt",
        unknown: "Okänd",
        yes: "Ja",
        no: "Nej",
        no_board_data: "Inga uppgifter om styrelsen.",
        company_and_contacts: "🏢 Företag och kontakt",
        form: "Bolagsform:",
        registration: "Registrerat:",
        phone: "Telefon:",
        address: "Adress:",
        city_county: "Ort/Län:",
        taxes: "🧾 Skatter",
        employer: "Arbetsgivare:",
        financials: "💰 Ekonomi",
        revenue: "Omsättning",
        profit_before_tax: "Resultat e. fin.",
        net_profit: "Årets resultat",
        total_assets: "Summa tillgångar",
        categories: "🏷️ Kategorier",
        industry_and_board: "🏭 Verksamhet och styrelse",
        sni_code: "SNI (Kod: {code})",
        board: "👥 Styrelse",
        years: "år",
        advanced_filters: "Avancerade filter",
        min: "Min",
        max: "Max",
        company_phone: "Företagstelefon",
        board_phone: "Styrelsetelefon",
        any: "Alla",
        has_phone: "Har telefon",
        no_phone: "Ingen telefon",
        sni_description: "SNI-beskrivning",
        categories_filter: "Kategorier",
        select_placeholder: "Välj...",
        no_results_found: "Inga resultat",
        clear_filters: "Rensa",
        f_skatt_filter: "F-skatt",
        vat_filter: "Moms (VAT)",
        employer_filter: "Arbetsgivare",
        activity_description_label: "Verksamhetsbeskrivning",
        interaction: "📌 Interaktion",
        status: "Status",
        status_none: "Ingen",
        status_interested: "Intresserad",
        status_not_interested: "Ej intresserad",
        status_callback: "Återkomma",
        comment: "Kommentar",
        add_comment_placeholder: "Lägg till en kommentar...",
        show_favorites_only: "Visa endast favoriter",
        filter_by_status: "Filtrera efter status"
    }
};

export const sortOptions = [
    { value: 'name-asc', key: 'sort_name_asc' },
    { value: 'name-desc', key: 'sort_name_desc' },
    { value: 'revenue-desc', key: 'sort_revenue_desc' },
    { value: 'revenue-asc', key: 'sort_revenue_asc' },
    { value: 'profit_after_financial_items-desc', key: 'sort_profit_before_tax_desc' },
    { value: 'profit_after_financial_items-asc', key: 'sort_profit_before_tax_asc' },
    { value: 'net_profit-desc', key: 'sort_net_profit_desc' },
    { value: 'net_profit-asc', key: 'sort_net_profit_asc' },
    { value: 'total_assets-desc', key: 'sort_assets_desc' },
    { value: 'total_assets-asc', key: 'sort_assets_asc' },
    { value: 'date-desc', key: 'sort_date_desc' },
    { value: 'date-asc', key: 'sort_date_asc' },
];

export const GITHUB_DATA_FILES = [
    'merinfo_complete_bil.jsonl',
];

const REPO_BASE_URL = 'https://cdn.jsdelivr.net/gh/alshfu/merinfo_scraper@main/data/';

export const githubDatasets = GITHUB_DATA_FILES.map(fileName => ({
    name: fileName,
    download_url: `${REPO_BASE_URL}${fileName}`
}));
